[feat] 스터디 관리(정보 수정)에 대한 API를 구현한다
kgu-capstone/study-with-me-be pull request #131
Opened 2023-04-11 14:19 UTC by chaeeerish

- [X] 🔀 PR 제목의 형식을 잘 작성했나요? e.g. `[feat] PR을 등록한다.` 
- [X] 💯 테스트는 잘 통과했나요?
- [X] 🏗️ 정상적으로 프로그램이 동작하나요?
- [X] 🧹 불필요한 코드는 제거했나요?
- [X] 💭 이슈는 등록했나요?
- [X] 🏷️ 라벨은 등록했나요?

## 작업 내용
- 스터디 관리 API 작성
- 테스트 코드 작성

Closes #117

2023-04-11 15:14 UTC, sjiwon requested changes
고생하셨어요👏

2023-04-11 15:14 UTC, sjiwon commented on src/main/java/com/kgu/studywithme/study/controller/StudyApiController.java
> +@RequestMapping("/api")
class level에 requestMapping을 "/api"로 변경하라는게 아예 study를 빼는게 아니고 register는 PostMapping("/study")로 하고 수정은 PatchMapping("/studies/{studyId}")로 하라는 말이였어요

register -> POST /api/study
update -> PATCH /api/studies/{studyId}

2023-04-11 15:14 UTC, sjiwon commented on src/main/java/com/kgu/studywithme/study/domain/Study.java
> +    }
```java
// Study Entity
public void update(StudyName name, Description description, int capacity, Category category, StudyType type,
                   String province, String city, RecruitmentStatus recruitmentStatus, Set<String> hashtags) {
    this.name = name;
    this.description = description;
    this.participants.updateCapacity(capacity);
    this.category = category;
    this.type = type;
    this.recruitmentStatus = recruitmentStatus;
    if (type == OFFLINE) {
        this.area = StudyArea.of(province, city);
    }
    applyHashtags(hashtags);
}
```

```java
// Participants Vo
public void updateCapacity(int capacity) {
    if (getNumberOfApproveParticipants() > capacity) {
        throw StudyWithMeException.type(StudyErrorCode.CAPACITY_CANNOT_BE_LESS_THAN_MEMBERS);
    }
    this.capacity = Capacity.from(capacity);
}
```

2023-04-11 15:14 UTC, sjiwon commented on src/test/java/com/kgu/studywithme/study/service/StudyServiceTest.java
>  @DisplayName("Study [Service Layer] -> StudyRegisterService 테스트")
StudyRegisterService 테스트 -> StudyService 테스트

2023-04-11 15:35 UTC, chaeeerish commented on src/main/java/com/kgu/studywithme/study/controller/StudyApiController.java
> +    }
오 네네! 저는 수정 페이지 들어갈때 폼 채우는걸 요청하는 줄 알았어요! 지우겠습니다

2023-04-12 06:10 UTC, sjiwon approved these changes

2023-04-12 06:10 UTC, merged