[feature] 사용자별 피어리뷰 조회 API를 구현한다
kgu-capstone/study-with-me-be pull request #136
Opened 2023-04-14 10:12 UTC by chaeeerish

- [X] 🔀 PR 제목의 형식을 잘 작성했나요? e.g. `[feat] PR을 등록한다.` 
- [X] 💯 테스트는 잘 통과했나요?
- [X] 🏗️ 정상적으로 프로그램이 동작하나요?
- [X] 🧹 불필요한 코드는 제거했나요?
- [X] 💭 이슈는 등록했나요?
- [X] 🏷️ 라벨은 등록했나요?

## 작업 내용
- 사용자 피어리뷰 조회 API 구현
- 테스트 코드 작성

Closes #124

2023-04-14 12:27 UTC, sjiwon requested changes
고생하셨어요👏

2023-04-14 12:27 UTC, sjiwon commented on src/main/java/com/kgu/studywithme/member/controller/MemberInformationApiController.java
> +    public ResponseEntity<PeerReviewAssembler> getReviews(@PathVariable Long memberId, @ExtractPayload Long payloadId) {
익명 사용자는 못보고 로그인한 사용자만 여러 사용자들의 피어 리뷰를 보도록 결정하신건가요?

2023-04-14 12:27 UTC, sjiwon commented on src/main/java/com/kgu/studywithme/member/domain/review/PeerReviewRepository.java
> +    List<String> findContentByRevieweeId(@Param("memberId") Long memberId);
content는 공지사항이나 댓글에서도 사용하는 필드라서 findPeerReviewByMemberId가 더 나을거같은데 어떠세요?

2023-04-14 12:27 UTC, sjiwon commented on src/test/java/com/kgu/studywithme/member/domain/review/PeerReviewRepositoryTest.java
> +}
```java
@DisplayName("Member [Repository Layer] -> PeerReviewRepository 테스트")
public class PeerReviewRepositoryTest extends RepositoryTest {
    @Autowired
    private PeerReviewRepository peerReviewRepository;

    @Autowired
    private MemberRepository memberRepository;

    private Member reviewee;
    private final Member[] reviewers = new Member[5];

    @BeforeEach
    void setUp() {
        reviewee = memberRepository.save(JIWON.toMember());
        reviewers[0] = memberRepository.save(DUMMY1.toMember());
        reviewers[1] = memberRepository.save(DUMMY2.toMember());
        reviewers[2] = memberRepository.save(DUMMY3.toMember());
        reviewers[3] = memberRepository.save(DUMMY4.toMember());
        reviewers[4] = memberRepository.save(DUMMY5.toMember());
    }

    @Test
    @DisplayName("사용자의 PeerReview를 조회한다")
    void findContentByRevieweeId() {
        /* 3명 피어리뷰 */
        doReview(reviewers[0], reviewers[1], reviewers[2]);

        List<String> result1 = peerReviewRepository.findContentByRevieweeId(reviewee.getId());
        assertThat(result1).hasSize(3);
        assertThat(result1).containsExactly(
                "BEST! - " + reviewers[0].getId(),
                "BEST! - " + reviewers[1].getId(),
                "BEST! - " + reviewers[2].getId()
        );

        /* 추가 2명 피어리뷰 */
        doReview(reviewers[3], reviewers[4]);

        List<String> result2 = peerReviewRepository.findContentByRevieweeId(reviewee.getId());
        assertThat(result2).hasSize(5);
        assertThat(result2).containsExactly(
                "BEST! - " + reviewers[0].getId(),
                "BEST! - " + reviewers[1].getId(),
                "BEST! - " + reviewers[2].getId(),
                "BEST! - " + reviewers[3].getId(),
                "BEST! - " + reviewers[4].getId()
        );
    }

    private void doReview(Member... reviewers) {
        for (Member reviewer : reviewers) {
            reviewee.applyPeerReview(reviewer, "BEST! - " + reviewer.getId());
        }
    }
}
```
- 조회같은 테스트의 경우 케이스를 많이 넣고 하는게 좋은거같아요

2023-04-14 12:37 UTC, chaeeerish commented on src/main/java/com/kgu/studywithme/member/controller/MemberInformationApiController.java
> +    public ResponseEntity<PeerReviewAssembler> getReviews(@PathVariable Long memberId, @ExtractPayload Long payloadId) {
로그인하지 않은 사용자가 볼 수 있는 페이지가 어디까지죠? 스터디 세부페이지까지 인 것 같은데,, 
어떤 페이지에서든지 사람의 이름을 클릭하면 사용자 정보에 대한 모달이 뜨나요?

2023-04-14 12:39 UTC, chaeeerish commented on src/main/java/com/kgu/studywithme/member/controller/MemberInformationApiController.java
> +    public ResponseEntity<PeerReviewAssembler> getReviews(@PathVariable Long memberId, @ExtractPayload Long payloadId) {
그렇게 되면, 세부페이지에서 팀장 혹은 졸업생들의 정보까지 볼 수 있겠네요
그렇게 할까요?

2023-04-14 12:43 UTC, chaeeerish commented on src/test/java/com/kgu/studywithme/member/domain/review/PeerReviewRepositoryTest.java
> +}
```java
    public static PeerReview doReview(Member reviewee, Member reviewer, String content) {
        return new PeerReview(reviewee, reviewer, content);
    }
``` 
PeerReview 도메인 클래스에 같은 이름의 메서드 있는데 상관없나요?

2023-04-14 12:46 UTC, sjiwon commented on src/test/java/com/kgu/studywithme/member/domain/review/PeerReviewRepositoryTest.java
> +}
네이밍은 자유롭게 그 메소드가 뭘하는지 파악할 수 있을정도면 돼요. 저거는 그냥 예시로 대충 써드린거에요

2023-04-14 12:47 UTC, sjiwon commented on src/main/java/com/kgu/studywithme/member/controller/MemberInformationApiController.java
> +    public ResponseEntity<PeerReviewAssembler> getReviews(@PathVariable Long memberId, @ExtractPayload Long payloadId) {
어쨌든 각 사용자간의 리뷰니까 로그인한 사람만 보도록 하는게 맞을거 같고 유지해도 될거같아요

2023-04-14 12:50 UTC, chaeeerish commented on src/test/java/com/kgu/studywithme/member/domain/review/PeerReviewRepositoryTest.java
> +}
네네ㅋㅋ

2023-04-14 13:20 UTC, chaeeerish commented on src/main/java/com/kgu/studywithme/member/domain/review/PeerReviewRepository.java
> +    List<String> findContentByRevieweeId(@Param("memberId") Long memberId);
네네! 푸시했는데 한번 봐주실 수 있나요?

2023-04-14 13:26 UTC, chaeeerish commented on src/main/java/com/kgu/studywithme/member/domain/review/PeerReviewRepository.java
> +    List<String> findContentByRevieweeId(@Param("memberId") Long memberId);
아앗 해결했어요..ㅎ

2023-04-15 09:49 UTC, sjiwon approved these changes

2023-04-15 09:49 UTC, merged