[feat] 사용자간 피어리뷰를 위한 API를 구현한다
kgu-capstone/study-with-me-be pull request #139
Opened 2023-04-15 17:59 UTC by chaeeerish

- [X] 🔀 PR 제목의 형식을 잘 작성했나요? e.g. `[feat] PR을 등록한다.` 
- [X] 💯 테스트는 잘 통과했나요?
- [X] 🏗️ 정상적으로 프로그램이 동작하나요?
- [X] 🧹 불필요한 코드는 제거했나요?
- [X] 💭 이슈는 등록했나요?
- [X] 🏷️ 라벨은 등록했나요?

## 작업 내용
- 피어리뷰 등록 API
- 피어리뷰 수정 API
- 테스트 코드 작성

Closes #119

2023-04-15 18:25 UTC, chaeeerish commented on src/test/java/com/kgu/studywithme/member/domain/review/PeerReviewRepositoryTest.java
> +    }
반복문으로 합치는게 나을까요?

2023-04-16 04:36 UTC, sjiwon requested changes
고생하셨어요👏

2023-04-16 04:36 UTC, sjiwon commented on src/test/java/com/kgu/studywithme/member/service/MemberServiceTest.java
> +    class writeReview {
```java
@Nested
@DisplayName("피어리뷰 등록")
class writeReview {
    private Member host;
    private Member outsider;
    private final Member[] participants = new Member[3];

    @BeforeEach
    void setUp() {
        host = memberRepository.save(JIWON.toMember());
        outsider = memberRepository.save(GHOST.toMember());
        participants[0] = memberRepository.save(DUMMY1.toMember());
        participants[1] = memberRepository.save(DUMMY2.toMember());
        participants[2] = memberRepository.save(DUMMY3.toMember());

        Study study = studyRepository.save(TOEIC.toOnlineStudy(host));
        beParticipation(study, participants[0], participants[1], participants[2]);

        weekRepository.save(STUDY_WEEKLY_1.toWeekWithAssignment(study));
        study.recordAttendance(1, NON_ATTENDANCE, host);
        study.recordAttendance(1, NON_ATTENDANCE, participants[0]);
        study.recordAttendance(1, NON_ATTENDANCE, participants[1]);
        study.recordAttendance(1, NON_ATTENDANCE, participants[2]);
    }

    @Test
    @DisplayName("해당 사용자에 대해 두 번이상 피어리뷰를 남길 수 없다")
    void alreadyReview() {
        // given
        memberService.writeReview(participants[0].getId(), participants[1].getId(), "GOOD-1");

        // when - then
        assertThatThrownBy(() -> memberService.writeReview(participants[0].getId(), participants[1].getId(), "GOOD-2"))
                .isInstanceOf(StudyWithMeException.class)
                .hasMessage(MemberErrorCode.ALREADY_REVIEW.getMessage());
    }

    @Test
    @DisplayName("본인에게 피어리뷰를 남길 수 없다")
    void selfReviewNotAllowed() {
        assertThatThrownBy(() -> memberService.writeReview(participants[0].getId(), participants[0].getId(), "GOOD"))
                .isInstanceOf(StudyWithMeException.class)
                .hasMessage(MemberErrorCode.SELF_REVIEW_NOT_ALLOWED.getMessage());
    }

    @Test
    @DisplayName("함께 스터디를 진행한 기록이 없다면 피어리뷰를 남길 수 없다")
    void commonStudyNotFound() {
        assertThatThrownBy(() -> memberService.writeReview(participants[0].getId(), outsider.getId(), "BAD"))
                .isInstanceOf(StudyWithMeException.class)
                .hasMessage(MemberErrorCode.COMMON_STUDY_NOT_FOUND.getMessage());
        assertThatThrownBy(() -> memberService.writeReview(outsider.getId(), participants[0].getId(), "BAD"))
                .isInstanceOf(StudyWithMeException.class)
                .hasMessage(MemberErrorCode.COMMON_STUDY_NOT_FOUND.getMessage());

        assertDoesNotThrow(() -> memberService.writeReview(host.getId(), participants[1].getId(), "GOOD"));
        assertDoesNotThrow(() -> memberService.writeReview(participants[1].getId(), host.getId(), "GOOD"));
    }

    @Test
    @DisplayName("피어리뷰 등록에 성공한다")
    void success() {
        // when
        memberService.writeReview(host.getId(), participants[0].getId(), "GOOD-" + participants[0].getId());
        memberService.writeReview(host.getId(), participants[1].getId(), "GOOD-" + participants[1].getId());
        memberService.writeReview(participants[0].getId(), participants[2].getId(), "GOOD-" + participants[2].getId());
        memberService.writeReview(participants[1].getId(), participants[2].getId(), "GOOD-" + participants[2].getId());

        // then
        assertThatWriteReviewMatch(host, participants[0], participants[1]);
        assertThatWriteReviewMatch(participants[0], participants[2]);
        assertThatWriteReviewMatch(participants[1], participants[2]);
    }

    private void assertThatWriteReviewMatch(Member reviewee, Member... reviewers) {
        for (Member reviewer : reviewers) {
            PeerReview peerReview = peerReviewRepository.findByRevieweeIdAndReviewerId(reviewee.getId(), reviewer.getId())
                    .orElseThrow();

            assertAll(
                    () -> assertThat(peerReview.getReviewee()).isEqualTo(reviewee),
                    () -> assertThat(peerReview.getReviewer()).isEqualTo(reviewer),
                    () -> assertThat(peerReview.getContent()).isEqualTo("GOOD-" + reviewer.getId())
            );
        }
    }
}
```
- 이렇게 수정하는거는 어떤가요?

2023-04-16 04:36 UTC, sjiwon commented on src/test/java/com/kgu/studywithme/member/service/MemberServiceTest.java
> +    class updateReview {
```java
@Nested
@DisplayName("피어리뷰 수정")
class updateReview {
    private static final String REVIEW = "GOOD";
    private static final String UPDATE_REVIEW = "VERY GOOD";

    private Member host;
    private final Member[] participants = new Member[2];

    @BeforeEach
    void setUp() {
        host = memberRepository.save(JIWON.toMember());
        participants[0] = memberRepository.save(DUMMY1.toMember());
        participants[1] = memberRepository.save(DUMMY2.toMember());

        Study study = studyRepository.save(TOEIC.toOnlineStudy(host));
        beParticipation(study, participants[0], participants[1]);

        weekRepository.save(STUDY_WEEKLY_1.toWeekWithAssignment(study));
        study.recordAttendance(1, NON_ATTENDANCE, host);
        study.recordAttendance(1, NON_ATTENDANCE, participants[0]);
        study.recordAttendance(1, NON_ATTENDANCE, participants[1]);

        // review
        host.applyPeerReview(participants[0], REVIEW);
    }

    @Test
    @DisplayName("피어리뷰 기록이 없다면 수정할 수 없다")
    void reviewNotFound() {
        assertThatThrownBy(() -> memberService.updateReview(host.getId(), participants[1].getId(), UPDATE_REVIEW))
                .isInstanceOf(StudyWithMeException.class)
                .hasMessage(MemberErrorCode.REVIEW_NOT_FOUND.getMessage());

        assertDoesNotThrow(() -> memberService.updateReview(host.getId(), participants[0].getId(), UPDATE_REVIEW));
    }

    @Test
    @DisplayName("피어리뷰 수정에 성공한다")
    void success() {
        // when
        memberService.updateReview(host.getId(), participants[0].getId(), UPDATE_REVIEW);

        // then
        PeerReview findPeerReview = peerReviewRepository.findByRevieweeIdAndReviewerId(host.getId(), participants[0].getId()).orElseThrow();
        assertAll(
                () -> assertThat(findPeerReview.getReviewee()).isEqualTo(host),
                () -> assertThat(findPeerReview.getReviewer()).isEqualTo(participants[0]),
                () -> assertThat(findPeerReview.getContent()).isEqualTo(UPDATE_REVIEW)
        );
    }
}
```

2023-04-16 04:36 UTC, sjiwon commented on src/test/java/com/kgu/studywithme/member/service/MemberServiceTest.java
> +    }
```java
private void beParticipation(Study study, Member... members) {
    for (Member member : members) {
        study.applyParticipation(member);
        study.approveParticipation(member);
    }
}
```

2023-04-16 06:25 UTC, chaeeerish commented on src/main/java/com/kgu/studywithme/member/exception/MemberErrorCode.java
> +    REVIEW_NOT_FOUND(HttpStatus.CONFLICT, "MEMBER_013", "피어리뷰를 찾을 수 없습니다."),
고칠께요!

2023-04-16 08:16 UTC, chaeeerish commented on src/main/java/com/kgu/studywithme/member/service/MemberService.java
> +    }
한번 해볼께요..!
쿼리로 한 번에 뽑아서 객체로 다루는 방법은 괜찮은가요?

2023-04-16 08:43 UTC, sjiwon commented on src/main/java/com/kgu/studywithme/member/service/MemberService.java
> +    }
필요한 정보가 2명이 사용자간의 참여 스터디 정보 & 출석 주차면 studyId, week만 쿼리로 가져오고 studyId기준으로 List<Integer> week을 mapping해서 비교하면 될거같아요

다 가져와서 해도 기능은 동작하겠지만 필요한것만 뽑는게 좋지 않을까요

2023-04-16 10:16 UTC, chaeeerish commented on src/main/java/com/kgu/studywithme/member/service/MemberService.java
> +    }
네네!

2023-04-16 13:30 UTC, chaeeerish commented on src/main/java/com/kgu/studywithme/member/service/MemberService.java
> +    }
```java
public class QStudyWeeksDTO extends ConstructorExpression<StudyWeeksDTO> {

    private static final long serialVersionUID = -1343566883L;

    public QStudyWeeksDTO(com.querydsl.core.types.Expression<Long> studyId, com.querydsl.core.types.Expression<? extends java.util.List<Integer>> weeks) {
        super(StudyWeeksDTO.class, new Class<?>[]{long.class, java.util.List.class}, studyId, weeks);
    }
}
```

select(new QStudyWeeksDTO(~)) 로 해보려고 했는데, weeks를 list로 만들어서 넣는 과정에서 에러가 자꾸 나서 일단 Tuple로 받아서 List<Tuple> -> List<StudyWeeksDTO> 변환했어요..!

2023-04-17 02:00 UTC, sjiwon approved these changes

2023-04-17 02:01 UTC, merged